# load libraries

pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}

pkgTest("SDMTools")
pkgTest("ncdf4")
# pkgTest("RCurl")
pkgTest("raster")
pkgTest("data.table")
# pkgTest("lunar")
pkgTest("R.utils")
pkgTest("RColorBrewer")
pkgTest("gbm")
pkgTest("colorRamps")
pkgTest("maps")
pkgTest("mapdata")
pkgTest("tweedie")
pkgTest("mgcv")
pkgTest("gamm4")
pkgTest("sp")
pkgTest("rgdal")
pkgTest("fields")
pkgTest("maptools")
# pkgTest("adehabitatHR")
# pkgTest("adehabitatHS")
# pkgTest("adehabitatLT")
# pkgTest("adehabitatMA")
pkgTest("tidyverse")
pkgTest("magrittr")
pkgTest("dismo")
pkgTest("caret")
pkgTest("mlbench")
pkgTest("cowplot")
pkgTest("gdata")
pkgTest("plotly")
# pkgTest("tiff")
pkgTest("MASS")
pkgTest("ggmap")
pkgTest("d3heatmap")
pkgTest("rasterVis")
pkgTest("corrplot")
pkgTest("factoextra")
pkgTest("gplots")
pkgTest("sf")
# pkgTest("rnaturalearth")
# pkgTest("rnaturalearthdata")
pkgTest("rgeos")
pkgTest("glue")
library(parallel)
pkgTest("fasterize")
pkgTest("lubridate")
pkgTest("rgeos")
pkgTest("ggExtra")
pkgTest("ggspatial")
pkgTest("RStoolbox")
pkgTest("gtable")
pkgTest("grid")
pkgTest("scales")
pkgTest("egg")
pkgTest("zoo")
pkgTest("ggnewscale")
pkgTest("foreach")
pkgTest("doParallel")
pkgTest("DescTools")
pkgTest("ggpubr")
pkgTest("igraph")
pkgTest("viridis")
pkgTest("patchwork")
pkgTest("hrbrthemes")
pkgTest("circlize")
pkgTest("chorddiag")
pkgTest("ggraph")

